In [16]:
import pandas as pd
pd.set_option("display.max_rows", None)

In [3]:
log = pd.read_csv("scrape_log.csv")

In [4]:
log

,fixture_id,status,http_status,file_name,error,attempts,timestamp
0,70600,success,200,fixture_70600.json,NaN,1.0,2026-07-21T16:22:23-04:00
1,71800,failed_500,500,NaN,<!DOCTYPE html>\n<html>\n <head>\n <...,3.0,2026-07-21T16:22:23-04:00
2,70598,success,200,fixture_70598.json,NaN,1.0,2026-07-21T16:23:55-04:00
3,70599,success,200,fixture_70599.json,NaN,1.0,2026-07-21T16:23:57-04:00
4,70601,success,200,fixture_70601.json,NaN,1.0,2026-07-21T16:24:00-04:00
...,...,...,...,...,...,...,...
23496,72496,failed_500,500,NaN,<!DOCTYPE html>\n<html>\n <head>\n <...,NaN,2026-07-22T12:37:31-04:00
23497,72497,failed_500,500,NaN,<!DOCTYPE html>\n<html>\n <head>\n <...,NaN,2026-07-22T12:37:39-04:00
23498,72498,failed_500,500,NaN,<!DOCTYPE html>\n<html>\n <head>\n <...,NaN,2026-07-22T12:37:46-04:00
23499,72499,failed_500,500,NaN,<!DOCTYPE html>\n<html>\n <head>\n <...,NaN,2026-07-22T12:37:54-04:00
23500,72500,failed_500,500,NaN,<!DOCTYPE html>\n<html>\n <head>\n <...,NaN,2026-07-22T12:38:02-04:00

### Data Collection Report

In [6]:
#checking status
log['status'].value_counts()
# 2474 are failed_500. None are incomplete or unexpected in structure.

status
success       21027
failed_500     2474
Name: count, dtype: int64



| Metric                |  Value |
| --------------------- | -----: |
| Fixture IDs attempted | 23,501 |
| Successful JSONs      | 21,027 |
| Failed (500)          |  2,474 |
| Success rate          |  89.5% |

### Inspecting HTTP 500 entries

In [8]:
log_failed = log[log['status'] == 'failed_500']

In [9]:
len(log_failed)

2474

In [10]:
log_failed['fixture_id']

1        71800
66       49055
67       49056
117      49106
118      49107
         ...
23496    72496
23497    72497
23498    72498
23499    72499
23500    72500
Name: fixture_id, Length: 2474, dtype: int64

In [17]:
# finding consecutive chunks of failed responses and putting them into a data frame
failed_ids = sorted(log_failed["fixture_id"].tolist()) # sort failed ids in a list from small to large numbers
chunks = []

start = failed_ids[0]
prev = failed_ids[0]

for current in failed_ids[1:]:
    if current == prev + 1:
        prev = current
    else:
        chunks.append((start, prev, prev - start + 1))
        start = current
        prev = current

chunks.append((start, prev, prev - start + 1)) #to save the last iteration

chunks_df = pd.DataFrame(
    chunks,
    columns=["start", "end", "length"]
)

chunks_df.sort_values("length", ascending=False) #sort by longest chunk

#"Is this number exactly one more than the previous one?"
# Yes → we're still inside the same chunk, so extend it.
# No → the previous chunk is finished, save it and start a new one

     start    end  length
186  56044  56319     276
187  56326  56591     266
614  72297  72500     204
208  57762  57833      72
185  55976  56035      60
360  62177  62235      59
405  63971  64027      57
601  71963  72003      41
410  64083  64121      39
496  67457  67494      38
463  66319  66354      36
21   49484  49513      30
586  71523  71552      30
445  65254  65281      28
406  64043  64070      28
61   50985  51012      28
76   51478  51501      24
492  67365  67388      24
20   49462  49482      21
606  72138  72156      19
411  64124  64140      17
507  68176  68192      17
267  59074  59089      16
485  67224  67239      16
495  67427  67441      15
34   49945  49959      15
237  58400  58413      14
461  66281  66293      13
579  71190  71202      13
608  72170  72182      13
596  71861  71872      12
13   49305  49316      12
320  61478  61488      11
607  72158  72168      11
18   49423  49433      11
60   50974  50983      10
266  58958  58967      10
479  66833  66841       9
174  55665  55673       9
583  71257  71265       9
70   51372  51379       8
464  66397  66404       8
168  55386  55393       8
603  72026  72033       8
584  71267  71274       8
175  55692  55698       7
58   50936  50941       6
107  52583  52588       6
515  68452  68457       6
493  67390  67394       5
11   49212  49216       5
191  56971  56975       5
592  71773  71777       5
539  68901  68905       5
359  62139  62143       5
503  67926  67930       5
390  63524  63528       5
459  66205  66208       4
180  55886  55889       4
396  63615  63618       4
228  58183  58186       4
449  65401  65404       4
354  62042  62045       4
468  66497  66500       4
407  64073  64076       4
365  62438  62441       4
357  62073  62076       4
456  66092  66095       4
531  68707  68710       4
555  70182  70185       4
506  68170  68173       4
591  71766  71769       4
10   49201  49204       4
582  71243  71246       4
274  59691  59693       3
278  59846  59848       3
33   49891  49893       3
106  52495  52497       3
51   50816  50818       3
521  68539  68541       3
367  62555  62557       3
197  57292  57294       3
196  57287  57289       3
115  53085  53087       3
118  53162  53164       3
581  71238  71240       3
500  67908  67910       3
167  55382  55384       3
119  53180  53182       3
86   52072  52074       3
446  65370  65372       3
57   50914  50916       3
447  65374  65376       3
173  55656  55658       3
169  55407  55409       3
72   51391  51393       3
181  55900  55902       3
427  64873  64875       3
475  66552  66554       3
295  61098  61099       2
259  58707  58708       2
305  61142  61143       2
268  59283  59284       2
611  72218  72219       2
572  70854  70855       2
573  70902  70903       2
609  72204  72205       2
594  71822  71823       2
178  55783  55784       2
245  58648  58649       2
188  56731  56732       2
576  71160  71161       2
577  71166  71167       2
578  71170  71171       2
207  57667  57668       2
202  57515  57516       2
1    49106  49107       2
585  71508  71509       2
193  57009  57010       2
194  57018  57019       2
470  66510  66511       2
312  61384  61385       2
402  63889  63890       2
472  66526  66527       2
473  66534  66535       2
460  66245  66246       2
474  66542  66543       2
458  66165  66166       2
159  55062  55063       2
452  65782  65783       2
482  67092  67093       2
430  64895  64896       2
428  64877  64878       2
421  64656  64657       2
409  64080  64081       2
502  67917  67918       2
505  68142  68143       2
509  68251  68252       2
317  61417  61418       2
393  63604  63605       2
518  68520  68521       2
385  63311  63312       2
379  63138  63139       2
376  62990  62991       2
366  62447  62448       2
536  68783  68784       2
546  69441  69442       2
353  61978  61979       2
471  66518  66519       2
325  61636  61637       2
321  61515  61516       2
556  70216  70217       2
319  61434  61435       2
337  61885  61886       2
0    49055  49056       2
98   52284  52285       2
150  54524  54525       2
141  53927  53928       2
26   49657  49658       2
27   49663  49664       2
35   49968  49969       2
130  53592  53593       2
39   50036  50037       2
45   50536  50537       2
124  53427  53428       2
54   50867  50868       2
65   51292  51293       2
68   51364  51365       2
75   51471  51472       2
105  52492  52493       2
89   52132  52133       2
101  52346  52347       2
16   49417  49418       2
46   50575  50576       2
152  54611  54612       2
4    49125  49126       2
454  66078  66078       1
3    49112  49112       1
69   51367  51367       1
462  66305  66305       1
71   51384  51384       1
73   51447  51447       1
74   51467  51467       1
610  72213  72213       1
457  66102  66102       1
77   51510  51510       1
455  66083  66083       1
453  65975  65975       1
466  66481  66481       1
78   51535  51535       1
451  65778  65778       1
450  65434  65434       1
79   51549  51549       1
448  65383  65383       1
80   51576  51576       1
81   51700  51700       1
82   51869  51869       1
444  65207  65207       1
443  65029  65029       1
442  65026  65026       1
465  66423  66423       1
467  66495  66495       1
440  65020  65020       1
481  67090  67090       1
491  67346  67346       1
490  67322  67322       1
489  67316  67316       1
488  67310  67310       1
487  67307  67307       1
486  67300  67300       1
5    49146  49146       1
484  67181  67181       1
483  67170  67170       1
55   50906  50906       1
480  66894  66894       1
67   51327  51327       1
56   50912  50912       1
478  66790  66790       1
477  66690  66690       1
476  66602  66602       1
59   50956  50956       1
62   51038  51038       1
63   51199  51199       1
64   51260  51260       1
66   51313  51313       1
469  66507  66507       1
441  65022  65022       1
598  71904  71904       1
52   50834  50834       1
414  64349  64349       1
412  64215  64215       1
88   52108  52108       1
612  72257  72257       1
613  72271  72271       1
90   52142  52142       1
408  64078  64078       1
91   52170  52170       1
92   52175  52175       1
93   52189  52189       1
404  63944  63944       1
403  63932  63932       1
94   52219  52219       1
401  63881  63881       1
400  63808  63808       1
399  63788  63788       1
398  63663  63663       1
397  63641  63641       1
95   52266  52266       1
395  63611  63611       1
394  63608  63608       1
96   52271  52271       1
392  63602  63602       1
391  63578  63578       1
413  64300  64300       1
415  64364  64364       1
439  65015  65015       1
416  64377  64377       1
438  64994  64994       1
437  64986  64986       1
436  64968  64968       1
435  64955  64955       1
434  64938  64938       1
433  64918  64918       1
432  64916  64916       1
431  64909  64909       1
83   51882  51882       1
429  64886  64886       1
84   51998  51998       1
85   52044  52044       1
426  64840  64840       1
425  64821  64821       1
424  64810  64810       1
423  64800  64800       1
422  64770  64770       1
87   52076  52076       1
420  64650  64650       1
419  64534  64534       1
418  64502  64502       1
417  64396  64396       1
2    49110  49110       1
53   50854  50854       1
494  67397  67397       1
597  71902  71902       1
30   49796  49796       1
570  70645  70645       1
569  70626  70626       1
568  70501  70501       1
567  70498  70498       1
566  70495  70495       1
565  70484  70484       1
564  70477  70477       1
563  70369  70369       1
562  70352  70352       1
561  70232  70232       1
560  70230  70230       1
559  70226  70226       1
558  70223  70223       1
557  70221  70221       1
31   49799  49799       1
32   49859  49859       1
554  70158  70158       1
553  70143  70143       1
552  69875  69875       1
551  69786  69786       1
550  69709  69709       1
549  69607  69607       1
548  69604  69604       1
571  70767  70767       1
29   49682  49682       1
50   50814  50814       1
574  71056  71056       1
9    49198  49198       1
595  71825  71825       1
12   49295  49295       1
593  71800  71800       1
14   49339  49339       1
15   49357  49357       1
590  71763  71763       1
589  71759  71759       1
588  71695  71695       1
587  71619  71619       1
599  71909  71909       1
17   49421  49421       1
600  71924  71924       1
19   49454  49454       1
22   49559  49559       1
23   49564  49564       1
24   49567  49567       1
580  71236  71236       1
25   49580  49580       1
8    49195  49195       1
602  72010  72010       1
28   49671  49671       1
575  71155  71155       1
547  69542  69542       1
545  69381  69381       1
544  69197  69197       1
543  69163  69163       1
517  68474  68474       1
516  68459  68459       1
41   50042  50042       1
514  68442  68442       1
513  68438  68438       1
512  68434  68434       1
511  68413  68413       1
510  68343  68343       1
42   50098  50098       1
508  68232  68232       1
43   50106  50106       1
44   50275  50275       1
605  72128  72128       1
504  67973  67973       1
389  63522  63522       1
47   50601  50601       1
501  67913  67913       1
48   50724  50724       1
499  67850  67850       1
498  67618  67618       1
497  67605  67605       1
6    49170  49170       1
49   50751  50751       1
40   50040  50040       1
519  68534  68534       1
520  68536  68536       1
532  68712  68712       1
542  69153  69153       1
541  69102  69102       1
540  69023  69023       1
36   49979  49979       1
538  68886  68886       1
537  68824  68824       1
37   50007  50007       1
535  68780  68780       1
534  68778  68778       1
533  68726  68726       1
38   50034  50034       1
604  72074  72074       1
530  68704  68704       1
529  68670  68670       1
7    49173  49173       1
528  68641  68641       1
527  68620  68620       1
526  68595  68595       1
525  68592  68592       1
524  68552  68552       1
523  68548  68548       1
522  68543  68543       1
97   52282  52282       1
155  54766  54766       1
388  63508  63508       1
215  58086  58086       1
241  58596  58596       1
240  58471  58471       1
239  58469  58469       1
238  58457  58457       1
131  53595  53595       1
236  58388  58388       1
235  58315  58315       1
234  58308  58308       1
233  58286  58286       1
232  58280  58280       1
231  58277  58277       1
230  58272  58272       1
229  58268  58268       1
132  53600  53600       1
227  58179  58179       1
226  58172  58172       1
225  58169  58169       1
224  58166  58166       1
223  58162  58162       1
222  58157  58157       1
221  58153  58153       1
220  58151  58151       1
219  58144  58144       1
218  58101  58101       1
217  58093  58093       1
242  58612  58612       1
243  58640  58640       1
244  58644  58644       1
129  53581  53581       1
270  59383  59383       1
269  59379  59379       1
126  53501  53501       1
127  53516  53516       1
128  53563  53563       1
265  58913  58913       1
264  58911  58911       1
263  58771  58771       1
262  58769  58769       1
261  58766  58766       1
260  58759  58759       1
258  58701  58701       1
246  58652  58652       1
257  58698  58698       1
256  58693  58693       1
255  58689  58689       1
254  58687  58687       1
253  58680  58680       1
252  58677  58677       1
251  58674  58674       1
250  58670  58670       1
249  58665  58665       1
248  58663  58663       1
247  58659  58659       1
216  58088  58088       1
214  58072  58072       1
387  63452  63452       1
213  58053  58053       1
183  55922  55922       1
182  55907  55907       1
145  54174  54174       1
146  54177  54177       1
179  55882  55882       1
147  54235  54235       1
177  55771  55771       1
176  55707  55707       1
148  54406  54406       1
149  54417  54417       1
172  55635  55635       1
171  55516  55516       1
170  55449  55449       1
151  54561  54561       1
153  54712  54712       1
166  55281  55281       1
165  55266  55266       1
164  55224  55224       1
163  55110  55110       1
162  55096  55096       1
161  55093  55093       1
160  55090  55090       1
154  54720  54720       1
158  54931  54931       1
157  54800  54800       1
184  55947  55947       1
144  54172  54172       1
143  54139  54139       1
201  57442  57442       1
212  57987  57987       1
211  57903  57903       1
210  57853  57853       1
209  57839  57839       1
133  53602  53602       1
134  53674  53674       1
206  57665  57665       1
205  57574  57574       1
204  57572  57572       1
203  57570  57570       1
135  53689  53689       1
200  57356  57356       1
142  53953  53953       1
199  57323  57323       1
198  57319  57319       1
136  53743  53743       1
137  53769  53769       1
195  57045  57045       1
138  53883  53883       1
139  53890  53890       1
192  56993  56993       1
140  53912  53912       1
190  56913  56913       1
189  56887  56887       1
271  59385  59385       1
272  59389  59389       1
273  59391  59391       1
125  53499  53499       1
356  62071  62071       1
355  62069  62069       1
109  52623  52623       1
110  52934  52934       1
352  61974  61974       1
351  61972  61972       1
350  61968  61968       1
349  61965  61965       1
348  61925  61925       1
347  61923  61923       1
346  61920  61920       1
345  61917  61917       1
344  61914  61914       1
343  61907  61907       1
342  61904  61904       1
341  61902  61902       1
340  61899  61899       1
339  61896  61896       1
338  61893  61893       1
111  52939  52939       1
336  61876  61876       1
335  61831  61831       1
334  61792  61792       1
333  61787  61787       1
332  61782  61782       1
108  52618  52618       1
358  62083  62083       1
104  52487  52487       1
375  62973  62973       1
386  63448  63448       1
156  54794  54794       1
384  63305  63305       1
383  63297  63297       1
382  63294  63294       1
381  63189  63189       1
380  63142  63142       1
99   52288  52288       1
378  63047  63047       1
377  63015  63015       1
100  52342  52342       1
374  62823  62823       1
361  62240  62240       1
373  62816  62816       1
372  62807  62807       1
371  62796  62796       1
370  62789  62789       1
369  62693  62693       1
368  62639  62639       1
102  52394  52394       1
103  52419  52419       1
364  62399  62399       1
363  62397  62397       1
362  62290  62290       1
331  61780  61780       1
330  61776  61776       1
329  61769  61769       1
288  60844  60844       1
299  61118  61118       1
298  61112  61112       1
297  61108  61108       1
296  61103  61103       1
123  53285  53285       1
294  61091  61091       1
293  61081  61081       1
292  61075  61075       1
291  61073  61073       1
290  61064  61064       1
289  60940  60940       1
287  60682  60682       1
301  61125  61125       1
286  60593  60593       1
285  60517  60517       1
284  60036  60036       1
283  60022  60022       1
282  60020  60020       1
281  60012  60012       1
280  59879  59879       1
279  59866  59866       1
277  59820  59820       1
276  59731  59731       1
275  59722  59722       1
300  61120  61120       1
302  61127  61127       1
328  61762  61762       1
316  61403  61403       1
327  61756  61756       1
326  61685  61685       1
112  53026  53026       1
324  61588  61588       1
323  61583  61583       1
322  61567  61567       1
113  53029  53029       1
114  53058  53058       1
116  53097  53097       1
318  61430  61430       1
117  53150  53150       1
315  61398  61398       1
303  61131  61131       1
314  61395  61395       1
313  61391  61391       1
120  53189  53189       1
311  61380  61380       1
310  61373  61373       1
309  61369  61369       1
308  61305  61305       1
121  53200  53200       1
306  61148  61148       1
122  53202  53202       1
304  61135  61135       1
307  61271  61271       1

In [22]:
# checking cumulative share of each chunk to know how many I need to check to cover > 50% of this dataset
chunks_df = chunks_df.sort_values("length", ascending=False)

chunks_df["cum_failed"] = chunks_df["length"].cumsum()
chunks_df["cum_pct"] = (
    chunks_df["cum_failed"] / chunks_df["length"].sum() * 100
)

chunks_df.head(60)

     start    end  length  cum_failed    cum_pct
186  56044  56319     276         276  11.156023
187  56326  56591     266         542  21.907842
614  72297  72500     204         746  30.153597
208  57762  57833      72         818  33.063864
185  55976  56035      60         878  35.489086
360  62177  62235      59         937  37.873888
405  63971  64027      57         994  40.177850
601  71963  72003      41        1035  41.835085
410  64083  64121      39        1074  43.411479
496  67457  67494      38        1112  44.947454
463  66319  66354      36        1148  46.402587
21   49484  49513      30        1178  47.615198
586  71523  71552      30        1208  48.827809
445  65254  65281      28        1236  49.959580
406  64043  64070      28        1264  51.091350
61   50985  51012      28        1292  52.223120
76   51478  51501      24        1316  53.193209
492  67365  67388      24        1340  54.163298
20   49462  49482      21        1361  55.012126
606  72138  72156      19        1380  55.780113
411  64124  64140      17        1397  56.467259
507  68176  68192      17        1414  57.154406
267  59074  59089      16        1430  57.801132
485  67224  67239      16        1446  58.447858
495  67427  67441      15        1461  59.054163
34   49945  49959      15        1476  59.660469
237  58400  58413      14        1490  60.226354
461  66281  66293      13        1503  60.751819
579  71190  71202      13        1516  61.277284
608  72170  72182      13        1529  61.802749
596  71861  71872      12        1541  62.287793
13   49305  49316      12        1553  62.772838
18   49423  49433      11        1564  63.217462
320  61478  61488      11        1575  63.662086
607  72158  72168      11        1586  64.106710
60   50974  50983      10        1596  64.510914
266  58958  58967      10        1606  64.915117
479  66833  66841       9        1615  65.278901
174  55665  55673       9        1624  65.642684
583  71257  71265       9        1633  66.006467
584  71267  71274       8        1641  66.329830
603  72026  72033       8        1649  66.653193
70   51372  51379       8        1657  66.976556
168  55386  55393       8        1665  67.299919
464  66397  66404       8        1673  67.623282
175  55692  55698       7        1680  67.906225
58   50936  50941       6        1686  68.148747
107  52583  52588       6        1692  68.391269
515  68452  68457       6        1698  68.633791
493  67390  67394       5        1703  68.835893
11   49212  49216       5        1708  69.037995
191  56971  56975       5        1713  69.240097
592  71773  71777       5        1718  69.442199
539  68901  68905       5        1723  69.644301
359  62139  62143       5        1728  69.846403
503  67926  67930       5        1733  70.048504
390  63524  63528       5        1738  70.250606
555  70182  70185       4        1742  70.412288
531  68707  68710       4        1746  70.573969
459  66205  66208       4        1750  70.735651

### Getting only JSONs with HTTP status = success / 200

In [23]:
from pathlib import Path
import json

In [24]:
#keeping only those logs in scrape_log.csv where status is success
log_success = log[log["status"] == "success"]

In [25]:
# sanity check
len(log_success)

21027

In [29]:
# getting file names from the successful logs
success_files = log_success["file_name"].tolist()
success_files[1:10]

['fixture_70598.json',
 'fixture_70599.json',
 'fixture_70601.json',
 'fixture_70602.json',
 'fixture_70603.json',
 'fixture_70604.json',
 'fixture_70605.json',
 'fixture_70606.json',
 'fixture_70607.json']

In [32]:
# getting only successful jsons i.e. success_files in a list

json_folder = Path("./raw_match_centres") #from the root of this, go up till raw_match_centres

records = []

for file in success_files: #pick up the file names that have http status = success
    with open(json_folder / file, "r", encoding="utf-8") as f: #define their path!
        # / means join folder and filename. json_folder is data_collection/raw_match_centres and file is xxxx.json. so full path becomes data_collection/raw_match_centres/xxxxx.json.
        # open the file.
        # r means read only, don't edit it.
        # utf 8 is just some standard thing, ignore it.
        # f represents the existing open file. so with the opened file as f, append it to records.
        # json.load() converts file into python dictionary.
        records.append(json.load(f)) #add them to records!

In [33]:
# sanity check 
len(records)

21027

In [34]:
records[0].keys()

dict_keys(['fixture', 'teams_data', 'tournament', 'team1_players', 'team2_players', 'squad1_list', 'squad2_list', 'events', 'team1_score', 'team2_score', 'report', 'lineup1', 'lineup2', 'official1', 'official2', 'mvp', 'stats_available'])